"""Automate the LZX Industries Videomancer over USB MIDI and USB serial."""

from .const import (
    CROSSFADER_PARAM,
    EMBEDDED_PROGRAMS,
    OPERATORS,
    PARAM_COUNT,
    PARAM_DEFAULTS,
    PARAM_MAX,
    PARAM_MIN,
    PARK_REFERENCE,
    SWEEP_STEPS,
    VERSION,
    LogLevel,
    Operator,
    OperatorCategory,
    ParamKind,
    ParamRole,
    PresetBank,
    TransportState,
    classify_param,
    param_kind,
    resolve_operator,
)
from .device import ProgramParameter, Videomancer, open_midi, open_shell
from .discovery import DeviceInfo, find_device, find_devices
from .errors import (
    DeviceNotFoundError,
    FirmwareError,
    ShellError,
    ShellTimeoutError,
    TransportError,
    TransportUnavailableError,
    VmancerError,
)
from .firmware import (
    FIRMWARE_PRODUCT,
    FIRMWARE_REPO,
    Release,
    Uf2Image,
    inspect_uf2,
    list_releases,
    resolve_release,
    upgrade,
    version_key,
)
from .library import (
    LIBRARY_PRODUCT,
    LibraryEntry,
    download_library,
    install,
    install_library,
    library_entries,
    resolve_library,
)
from .midi import MidiController
from .programs import MANIFEST_PATH, ProgramEntry, ProgramManifest
from .shell import Reply, ShellClient, encode_preset, parse_line
from .video import VideoStatus

__version__ = VERSION

__all__ = [
    "CROSSFADER_PARAM",
    "DeviceInfo",
    "DeviceNotFoundError",
    "EMBEDDED_PROGRAMS",
    "FIRMWARE_PRODUCT",
    "FIRMWARE_REPO",
    "FirmwareError",
    "LIBRARY_PRODUCT",
    "LibraryEntry",
    "LogLevel",
    "MANIFEST_PATH",
    "MidiController",
    "OPERATORS",
    "Operator",
    "OperatorCategory",
    "PARAM_COUNT",
    "PARAM_DEFAULTS",
    "PARAM_MAX",
    "PARAM_MIN",
    "PARK_REFERENCE",
    "ParamKind",
    "ParamRole",
    "ProgramEntry",
    "ProgramManifest",
    "ProgramParameter",
    "PresetBank",
    "Release",
    "Reply",
    "SWEEP_STEPS",
    "ShellClient",
    "ShellError",
    "ShellTimeoutError",
    "TransportError",
    "TransportState",
    "TransportUnavailableError",
    "Uf2Image",
    "VideoStatus",
    "Videomancer",
    "VmancerError",
    "__version__",
    "classify_param",
    "download_library",
    "encode_preset",
    "find_device",
    "find_devices",
    "inspect_uf2",
    "install",
    "install_library",
    "library_entries",
    "list_releases",
    "open_midi",
    "open_shell",
    "param_kind",
    "parse_line",
    "resolve_library",
    "resolve_operator",
    "resolve_release",
    "upgrade",
    "version_key",
]
